### ISSUE TITLE
Ghost Armour sublplot: Corinth fails to trigger

### ISSUE THREAD

**Issue by lupine** [pentagram-u8/pentagram#1]
Per http://wiki.ultimacodex.com/wiki/Ultima_VIII_Walkthrough#Ghost_Armor_Subplot

Gwillem gets hot under the collar discussing ghosts, but Corinth doesn't gain a new dialogue option as a result, as it seems she should from the walkthrough.

**Comment by wjp** [comment]
The dialogue option is quite well hidden. I looked it up the last time this came up at: https://sourceforge.net/p/pentagram/bugs/185/

**Comment by lupine** [comment]
Ooops, sorry for the noise!

I wonder if there's an easy way to mirror all the sf issues to GitHub. They're almost as valuable as the code :)
